name: muzee
description: "Muzee develop by balua.dev"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #ui-icons
  flutter_remix: 0.0.3
  marquee: ^2.2.3
  #utils
  flutter_screenutil: ^5.9.3
  intl: 0.18.1
  go_router: 14.2.3
  video_player: ^2.9.2
  flutter_svg: ^2.0.10
  html_unescape: ^2.0.0
  xml2json: ^5.3.6
  fluttertoast: ^8.2.1
  shared_preferences: ^2.2.3
  quiver: ^3.2.2
  url_launcher: ^6.3.1
  collection: ^1.18.0
  html: ^0.15.4
  background_fetch: ^1.3.7
  # youtube_data_api: ^1.0.4
  google_mobile_ads: ^5.1.0

  #notification
  awesome_notifications_core: ^0.8.0
  awesome_notifications: 0.8.2

  #manage state
  flutter_bloc: 8.1.1
  equatable: 2.0.5

  #test
  #encrypt
  encrypt: ^5.0.1
  tuple: ^2.0.1

  #database
  isar: ^3.1.0
  isar_flutter_libs: any
  path_provider: any

  #network
  http: ^1.2.2 # some api has error can not fix, so use http lib
  dio: 5.4.0

  #ytb
  youtube_explode_dart: ^2.4.2
  audio_service: ^0.18.16
  audio_session: ^0.1.21
  cached_network_image: ^3.4.0
  flutter_appauth: ^9.0.1
  flutter_secure_storage: ^9.2.4
  wakelock_plus: ^1.2.8
  package_info_plus: ^8.0.2
  rate_my_app: ^2.2.0
  in_app_purchase: ^3.2.0

  #FIREBASE
  firebase_core: ^3.4.0
  firebase_remote_config: ^5.1.0
  firebase_messaging: ^15.1.0
  firebase_analytics: ^11.3.0
  cloud_firestore: ^5.4.0
  permission_handler: ^11.3.1

  #GAME SUPPORT
  #2048
  flutter_2048:
    path: ../flutter_2048
  sudoku:
    path: ../sudoku

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  #runnner
  build_runner: any

  #export-model
  json_serializable: ^6.6.0

  #gen-run-asset
  flutter_gen_runner: ^5.1.0

  analyzer: ^5.13.0
  #database
  isar_generator: any

dependency_overrides:
  dart_style:
  flutter_gen_core: 5.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    # - assets/data/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.TTF
        - asset: assets/fonts/Inter-Medium.TTF
        - asset: assets/fonts/Inter-Bold.TTF

flutter_gen:
  # output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    # lottie: true

  assets:
    enabled: true

  outputs:
    class_name: MyAssets
    package_parameter_enabled: false
    style: dot-delimiter

  fonts:
    enabled: true
    outputs:
      class_name: MyFonts

  colors:
    enabled: true
    outputs:
      class_name: MyColors
    inputs:
      - assets/colors/colors.xml
